# 5.6 try 语句块和异常处理

​	异常是指存在于运行时的返常行为，这些行为超出了函数正常功能的范围。典型的异常包括失去数据库连接以及遇到意外输入等。处理返常行为可能是设计所有系统最难的一部分。

​	异常处理机制为程序中异常检测和异常处理这两部分的协作提供支持。在C++中，异常处理包括：

* throw 表达式，异常检测部分使用 throw 表达式来表示它遇到了无法处理的问题。
* try 语句块。异常处理部分使用try语句块处理异常。try 语句块以关键字 try 开始，并以一个或多个catch子句结束。
* 一套异常类，用于在throw表达式和相关的catch子句之间传递异常的具体信息。

## 5.6.1 throw 表达式

​	程序异常检测部分使用 throw 表达式引发一个异常。throw 表达式包含关键字 throw 和紧随其后的一个表达式，其中表达式的类型就是抛出的异常类型。throw 表达式后面通常紧跟一个分号，从而构成一条表达式语句。

```c++
Sales_item item1, item2;
cin >> item1 >> item2;
// 首先检查 item1 和 item2 是否表示同一种书籍
if(item1.isbn() == item2.isbn())
{
    cout << item1 + item2 << endl;
    return 0;
} else{
    cerr << "data must refer to same ISBN" << endl;
    return -1;
}
```

 应该把对象相加的代码和用户交互（输入数据）的代码分离出来。

```c++
// 首先检查 item1 和 item2 是否表示同一种书籍
if(item1.isbn() ！= item2.isbn())
{
    throw runtime_error("data must refer to same ISBN");
}

cout << item1 + item2 <<endl;
```

## 5.6.2 try 语句块

通用语法：

```c++
try{
    program-statements
} catch (exception-declaration)
{
    handler-statements
} catch (exception-declaration)
{
    handler-statements
}
```

